env: aloha

env_args:
  n_agents: 10
  episode_limit: 20
  max_list_length: 5
  obs_last_action: False
  state_last_action: True
  seed: None

learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
t_max: 2005000
test_interval: 10000
test_nepisode: 300
test_greedy: True