env: disperse

env_args:
  n_agents: 12
  n_actions: 4
  initial_need: [0, 0, 0, 0]
  episode_limit: 10
  obs_last_action: False
  state_last_action: True

learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
t_max: 2005000
test_interval: 10000
test_nepisode: 300
test_greedy: True