env: sensor

env_args:
  n_preys: 3
  episode_limit: 10
  array_height: 3
  array_width: 5
  catch_reward: 3
  scan_cost: 1
  obs_last_action: False
  state_last_action: True

learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
t_max: 2005000
test_interval: 10000
test_nepisode: 300
test_greedy: True